name: 'Publish Python 🐍'
description: 'Publishes a Python project'

inputs:
  directory:
    description: 'The directory to publish'
    required: true
  version:
    description: 'The version to publish'
    required: true
  dry-run:
    description: 'Whether to perform a dry run'
    required: false
    default: 'false'
  pypi-api-key:
    description: 'The PyPI API key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Replace placeholder version
      shell: bash
      run: sed -i "s/0.0.0/${{ inputs.version }}/g" ${{ inputs.directory }}/pyproject.toml

    - name: Log project files
      shell: bash
      run: |
        echo "Project files:"
        ls -l ${{ inputs.directory }}
        echo "pyproject.toml:"
        cat ${{ inputs.directory }}/pyproject.toml

    - name: Build
      shell: bash
      run: uv build
      working-directory: ${{ inputs.directory }}

    - name: Publish
      if: ${{ inputs.dry-run == 'false' }}
      shell: bash
      run: uv publish -u "__token__" -p ${{ inputs.pypi-api-key }}
      working-directory: ${{ inputs.directory }}

    - name: Dry run
      if : ${{ inputs.dry-run == 'true' }}
      shell: bash
      run: |
        echo "Dry run"
        ls -l ${{ inputs.directory }}/dist

