name: 'Setup Python 🐍'
description: 'Sets up python environment'

inputs:
  directory:
    description: 'The directory to setup'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        # Install a specific version of uv.
        version: "0.5.10"

    - name: Install Python 3.12 using UV from ${{ inputs.directory }}
      shell: bash
      run: uv python install
      working-directory: ${{ inputs.directory }}

    - name: Install dependencies using UV
      shell: bash
      run: uv sync --all-extras --dev
      working-directory: ${{ inputs.directory }}

