name: Publish Olve.Utilities

on:
  push:
    branches:
      - master

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  resolve-version:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: ./.github/actions/setup-python

    - name: Resolving version
      uses: ./.github/actions/get-version
      id: version
      with:
        pre-release: true

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=1.0.0

    - name: Verify trimming
      run: dotnet publish ./tests/Olve.Utilities.Trimming --no-restore -c Release -r linux-x64 --self-contained

    - name: Test
      run: dotnet test --no-build -c Release

  publish_olve_utilities:
    runs-on: ubuntu-latest
    needs:
      - resolve-version
      - test
    steps:
    - uses: actions/checkout@v3

    - name: Echo Version variable
      shell: bash
      run: echo ${{ needs.resolve-version.outputs.VERSION }}

    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{ needs.resolve-version.outputs.VERSION }}

    - name: pack nuget packages
      run: dotnet pack ./src/Olve.Utilities --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=${{ needs.resolve-version.outputs.VERSION }}

    - name: upload nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

  publish_olve_sg_copy-properties:
    runs-on: ubuntu-latest
    needs:
      - resolve-version
      - test
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{ needs.resolve-version.outputs.VERSION }}

    - name: pack nuget packages
      run: dotnet pack ./src/source-generators/Olve.SG.CopyProperties --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=${{ needs.resolve-version.outputs.VERSION }}

    - name: upload nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
