name: Publish Olve.Utilities

on:
  push:
    branches:
      - master

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  resolve-version:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: ./.github/actions/setup-python

    - name: Resolving version
      uses: ./.github/actions/get-version
      id: version
      with:
        pre-release: true

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: .NET restore
      shell: bash
      run: |
        dotnet restore
        dotnet tool restore

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=1.0.0

    - name: Verify trimming
      run: dotnet publish ./tests/Olve.Utilities.Trimming --no-restore -c Release -r linux-x64 --self-contained

    - name: Test
      run: dotnet test --no-build -c Release

  publish_olve_utilities:
    runs-on: ubuntu-latest
    needs:
      - resolve-version
      - test
    steps:
    - name: Publish Olve.Utilities
      uses: ./.github/actions/publish-dotnet
      with:
        project: ./src/Olve.Utilities
        package-name: Olve.Utilities
        dry-run: true
        version: ${{ needs.resolve-version.outputs.VERSION }}

  publish_olve_sg_copy-properties:
    runs-on: ubuntu-latest
    needs:
      - resolve-version
      - test
    steps:

    - name: Publish Olve.SG.CopyProperties
      uses: ./.github/actions/publish-dotnet
      with:
        project: ./src/source-generators/Olve.SG.CopyProperties
        package-name: Olve.SG.CopyProperties
        dry-run: true
        version: ${{ needs.resolve-version.outputs.VERSION }}

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet
